################# English language ################
[en]
label = "English"
locale = "en-US"
direction = "ltr"
contentDir = "content/english"
weight = 1

################ Chinese language ##################
[zh]
label = "简体中文"
locale = "zh-CN"
direction = "ltr"
contentDir = "content/chinese"
weight = 6

################ Spanish language ##################
[es]
label = "Español"
locale = "es"
direction = "ltr"
contentDir = "content/spanish"
weight = 7

################ French language ###################
[fr]
label = "Français"
locale = "fr"
direction = "ltr"
contentDir = "content/french"
weight = 8
