[[main]]
name = "首页"
pageRef = "/"
weight = 10

[[main]]
name = "产品中心"
url = "/products/"
identifier = "products"
weight = 20

  [[main]]
  name = "塑料托盘"
  url = "/products/pallets/"
  parent = "products"
  weight = 21

  [[main]]
  name = "吹塑可嵌套塑料托盘"
  url = "/products/blow-molded-pallets/"
  parent = "products"
  weight = 22

  [[main]]
  name = "板条箱"
  url = "/products/crates/"   # 具体看你产品真实英文再定
  parent = "products"
  weight = 23

  [[main]]
  name = "可折叠塑料托盘箱"
  url = "/products/foldable-pallet-boxes/"
  parent = "products"
  weight = 24

  [[main]]
  name = "大型散装容器"
  url = "/products/bulk-containers/"
  parent = "products"
  weight = 25

  [[main]]
  name = "塑料垃圾桶"
  url = "/products/waste-bins/"
  parent = "products"
  weight = 26


[[main]]
name = "关于我们"
url = "/about/"
identifier = "about"
weight = 30


[[main]]
name = "资讯中心"
url = "/resources/"
identifier = "resources"
weight = 40

  [[main]]
  name = "客户案例"
  url = "/resources/case-studies/"
  parent = "resources"
  weight = 41

  [[main]]
  name = "文章"
  url = "/resources/insights/"
  parent = "resources"
  weight = 42

  [[main]]
  name = "下载中心"
  url = "/resources/downloads/"
  parent = "resources"
  weight = 43

  [[main]]
  name = "常见问题"
  url = "/resources/faq/"
  parent = "resources"
  weight = 44

  [[main]]
  name = "外贸术语表"
  url = "/resources/glossary/"
  parent = "resources"
  weight = 45

[[main]]
name = "联系我们"
url = "/contact/"
weight = 50
