baseURL = 'https://www.baohengplastic.com/'
languageCode = 'en-us'
title = 'Baoheng Plastic'
enableRobotsTXT = true

# 站点级参数已统一到 config/_default/params.toml

[languages]
  [languages.en]
    label = 'English'
    locale = 'en-US'
    direction = 'ltr'
    weight = 1
    contentDir = 'content/english'
  [languages.zh]
    label = '简体中文'
    locale = 'zh-CN'
    direction = 'ltr'
    weight = 6
    contentDir = 'content/chinese'
  [languages.es]
    label = 'Español'
    locale = 'es'
    direction = 'ltr'
    weight = 7
    contentDir = 'content/spanish'
  [languages.fr]
    label = 'Français'
    locale = 'fr'
    direction = 'ltr'
    weight = 8
    contentDir = 'content/french'
