baseURL = 'https://www.baohengplastic.com/'
languageCode = 'en-us'
title = 'Baoheng Plastic'
enableRobotsTXT = true

# 站点级参数已统一到 config/_default/params.toml

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    contentDir = 'content/english'
  [languages.zh]
    languageName = '中文'
    weight = 2
    contentDir = 'content/chinese'
